<?php

/**
 * AUTO GENERATED BY LUTICATE GENERATOR
 * ANY CHANGES WILL BE OVERWRITTEN
 */

namespace App\Http\DBO;

use Luticate\Utils\LuDbo;

class ImagesDbo extends LuDbo {

    public function jsonSerialize()
    {
        return array(
            "Id" => $this->_id,
            "UserId" => $this->_userId,
            "Path" => $this->_path
        );
    }

    public static function jsonDeserialize($json)
    {
        $dbo = new ImagesDbo();
        if (isset($json["Id"])) {
            $dbo->setId($json["Id"]);
        }
        if (isset($json["UserId"])) {
            $dbo->setUserId($json["UserId"]);
        }
        if (isset($json["Path"])) {
            $dbo->setPath($json["Path"]);
        }
        return $dbo;
    }

    public static function generateSample()
    {
        $dbo = new ImagesDbo();
        $dbo->setId(42);
        $dbo->setUserId(42);
        $dbo->setPath("sample string");
        return $dbo;
    }

    /**
     * @var integer
     */
    protected $_id;
    public function getId()
    {
        return $this->_id;
    }
    public function setId($value)
    {
        $this->_id = $value;
    }

    /**
     * @var integer
     */
    protected $_userId;
    public function getUserId()
    {
        return $this->_userId;
    }
    public function setUserId($value)
    {
        $this->_userId = $value;
    }

    /**
     * @var text
     */
    protected $_path;
    public function getPath()
    {
        return $this->_path;
    }
    public function setPath($value)
    {
        $this->_path = $value;
    }
}
